//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNEndpoints.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EpicEmail {
            get {
                return ((string)(this["EpicEmail"]));
            }
            set {
                this["EpicEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EpicPassword {
            get {
                return ((string)(this["EpicPassword"]));
            }
            set {
                this["EpicPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EN")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pakPath {
            get {
                return ((string)(this["pakPath"]));
            }
            set {
                this["pakPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string consumer_key {
            get {
                return ((string)(this["consumer_key"]));
            }
            set {
                this["consumer_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string consumer_secret {
            get {
                return ((string)(this["consumer_secret"]));
            }
            set {
                this["consumer_secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string access_token_key {
            get {
                return ((string)(this["access_token_key"]));
            }
            set {
                this["access_token_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string access_token_secret {
            get {
                return ((string)(this["access_token_secret"]));
            }
            set {
                this["access_token_secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 46, 46")]
        public global::System.Drawing.Color viewer_default_backcolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_default_backcolor"]));
            }
            set {
                this["viewer_default_backcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color viewer_default_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_default_forecolor"]));
            }
            set {
                this["viewer_default_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color viewer_BraceLight_backcolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_BraceLight_backcolor"]));
            }
            set {
                this["viewer_BraceLight_backcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color viewer_BraceLight_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_BraceLight_forecolor"]));
            }
            set {
                this["viewer_BraceLight_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color viewer_Cursor_Color {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Cursor_Color"]));
            }
            set {
                this["viewer_Cursor_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170, 170, 170")]
        public global::System.Drawing.Color viewer_Selection_backcolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Selection_backcolor"]));
            }
            set {
                this["viewer_Selection_backcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183, 183, 183")]
        public global::System.Drawing.Color viewer_linenumber_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_linenumber_forecolor"]));
            }
            set {
                this["viewer_linenumber_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color viewer_Json_PropertyName_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_PropertyName_forecolor"]));
            }
            set {
                this["viewer_Json_PropertyName_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color viewer_Json_String_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_String_forecolor"]));
            }
            set {
                this["viewer_Json_String_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color viewer_Json_Number_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_Number_forecolor"]));
            }
            set {
                this["viewer_Json_Number_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color viewer_Json_Operator_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_Operator_forecolor"]));
            }
            set {
                this["viewer_Json_Operator_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 191, 87")]
        public global::System.Drawing.Color viewer_Json_Comment_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_Comment_forecolor"]));
            }
            set {
                this["viewer_Json_Comment_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color viewer_Json_Uri_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_Uri_forecolor"]));
            }
            set {
                this["viewer_Json_Uri_forecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color viewer_Json_Boolean_forecolor {
            get {
                return ((global::System.Drawing.Color)(this["viewer_Json_Boolean_forecolor"]));
            }
            set {
                this["viewer_Json_Boolean_forecolor"] = value;
            }
        }
    }
}
